/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowTintRouteImport } from './routes/window-tint'
import { Route as TintLawsNewMexicoRouteImport } from './routes/tint-laws-new-mexico'
import { Route as TintRouteImport } from './routes/tint'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PpfRouteImport } from './routes/ppf'
import { Route as PaintProtectionFilmRouteImport } from './routes/paint-protection-film'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialWindowTintRouteImport } from './routes/commercial-window-tint'
import { Route as CeramicCoatingRouteImport } from './routes/ceramic-coating'
import { Route as CeramicRouteImport } from './routes/ceramic'
import { Route as AutoDetailingRouteImport } from './routes/auto-detailing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as BookConfirmedRouteImport } from './routes/book.confirmed'

const WindowTintRoute = WindowTintRouteImport.update({
  id: '/window-tint',
  path: '/window-tint',
  getParentRoute: () => rootRouteImport,
} as any)
const TintLawsNewMexicoRoute = TintLawsNewMexicoRouteImport.update({
  id: '/tint-laws-new-mexico',
  path: '/tint-laws-new-mexico',
  getParentRoute: () => rootRouteImport,
} as any)
const TintRoute = TintRouteImport.update({
  id: '/tint',
  path: '/tint',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PpfRoute = PpfRouteImport.update({
  id: '/ppf',
  path: '/ppf',
  getParentRoute: () => rootRouteImport,
} as any)
const PaintProtectionFilmRoute = PaintProtectionFilmRouteImport.update({
  id: '/paint-protection-film',
  path: '/paint-protection-film',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialWindowTintRoute = CommercialWindowTintRouteImport.update({
  id: '/commercial-window-tint',
  path: '/commercial-window-tint',
  getParentRoute: () => rootRouteImport,
} as any)
const CeramicCoatingRoute = CeramicCoatingRouteImport.update({
  id: '/ceramic-coating',
  path: '/ceramic-coating',
  getParentRoute: () => rootRouteImport,
} as any)
const CeramicRoute = CeramicRouteImport.update({
  id: '/ceramic',
  path: '/ceramic',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoDetailingRoute = AutoDetailingRouteImport.update({
  id: '/auto-detailing',
  path: '/auto-detailing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmedRoute = BookConfirmedRouteImport.update({
  id: '/book/confirmed',
  path: '/book/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auto-detailing': typeof AutoDetailingRoute
  '/ceramic': typeof CeramicRoute
  '/ceramic-coating': typeof CeramicCoatingRoute
  '/commercial-window-tint': typeof CommercialWindowTintRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/paint-protection-film': typeof PaintProtectionFilmRoute
  '/ppf': typeof PpfRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/tint': typeof TintRoute
  '/tint-laws-new-mexico': typeof TintLawsNewMexicoRoute
  '/window-tint': typeof WindowTintRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/book/': typeof BookIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auto-detailing': typeof AutoDetailingRoute
  '/ceramic': typeof CeramicRoute
  '/ceramic-coating': typeof CeramicCoatingRoute
  '/commercial-window-tint': typeof CommercialWindowTintRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/paint-protection-film': typeof PaintProtectionFilmRoute
  '/ppf': typeof PpfRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/tint': typeof TintRoute
  '/tint-laws-new-mexico': typeof TintLawsNewMexicoRoute
  '/window-tint': typeof WindowTintRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/book': typeof BookIndexRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auto-detailing': typeof AutoDetailingRoute
  '/ceramic': typeof CeramicRoute
  '/ceramic-coating': typeof CeramicCoatingRoute
  '/commercial-window-tint': typeof CommercialWindowTintRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/paint-protection-film': typeof PaintProtectionFilmRoute
  '/ppf': typeof PpfRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/tint': typeof TintRoute
  '/tint-laws-new-mexico': typeof TintLawsNewMexicoRoute
  '/window-tint': typeof WindowTintRoute
  '/book/confirmed': typeof BookConfirmedRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/book/': typeof BookIndexRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auto-detailing'
    | '/ceramic'
    | '/ceramic-coating'
    | '/commercial-window-tint'
    | '/contact'
    | '/gallery'
    | '/paint-protection-film'
    | '/ppf'
    | '/quote'
    | '/reviews'
    | '/tint'
    | '/tint-laws-new-mexico'
    | '/window-tint'
    | '/book/confirmed'
    | '/guides/$slug'
    | '/book/'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auto-detailing'
    | '/ceramic'
    | '/ceramic-coating'
    | '/commercial-window-tint'
    | '/contact'
    | '/gallery'
    | '/paint-protection-film'
    | '/ppf'
    | '/quote'
    | '/reviews'
    | '/tint'
    | '/tint-laws-new-mexico'
    | '/window-tint'
    | '/book/confirmed'
    | '/guides/$slug'
    | '/book'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auto-detailing'
    | '/ceramic'
    | '/ceramic-coating'
    | '/commercial-window-tint'
    | '/contact'
    | '/gallery'
    | '/paint-protection-film'
    | '/ppf'
    | '/quote'
    | '/reviews'
    | '/tint'
    | '/tint-laws-new-mexico'
    | '/window-tint'
    | '/book/confirmed'
    | '/guides/$slug'
    | '/book/'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AutoDetailingRoute: typeof AutoDetailingRoute
  CeramicRoute: typeof CeramicRoute
  CeramicCoatingRoute: typeof CeramicCoatingRoute
  CommercialWindowTintRoute: typeof CommercialWindowTintRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PaintProtectionFilmRoute: typeof PaintProtectionFilmRoute
  PpfRoute: typeof PpfRoute
  QuoteRoute: typeof QuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  TintRoute: typeof TintRoute
  TintLawsNewMexicoRoute: typeof TintLawsNewMexicoRoute
  WindowTintRoute: typeof WindowTintRoute
  BookConfirmedRoute: typeof BookConfirmedRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  BookIndexRoute: typeof BookIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window-tint': {
      id: '/window-tint'
      path: '/window-tint'
      fullPath: '/window-tint'
      preLoaderRoute: typeof WindowTintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tint-laws-new-mexico': {
      id: '/tint-laws-new-mexico'
      path: '/tint-laws-new-mexico'
      fullPath: '/tint-laws-new-mexico'
      preLoaderRoute: typeof TintLawsNewMexicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tint': {
      id: '/tint'
      path: '/tint'
      fullPath: '/tint'
      preLoaderRoute: typeof TintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppf': {
      id: '/ppf'
      path: '/ppf'
      fullPath: '/ppf'
      preLoaderRoute: typeof PpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paint-protection-film': {
      id: '/paint-protection-film'
      path: '/paint-protection-film'
      fullPath: '/paint-protection-film'
      preLoaderRoute: typeof PaintProtectionFilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-window-tint': {
      id: '/commercial-window-tint'
      path: '/commercial-window-tint'
      fullPath: '/commercial-window-tint'
      preLoaderRoute: typeof CommercialWindowTintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceramic-coating': {
      id: '/ceramic-coating'
      path: '/ceramic-coating'
      fullPath: '/ceramic-coating'
      preLoaderRoute: typeof CeramicCoatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ceramic': {
      id: '/ceramic'
      path: '/ceramic'
      fullPath: '/ceramic'
      preLoaderRoute: typeof CeramicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-detailing': {
      id: '/auto-detailing'
      path: '/auto-detailing'
      fullPath: '/auto-detailing'
      preLoaderRoute: typeof AutoDetailingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmed': {
      id: '/book/confirmed'
      path: '/book/confirmed'
      fullPath: '/book/confirmed'
      preLoaderRoute: typeof BookConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AutoDetailingRoute: AutoDetailingRoute,
  CeramicRoute: CeramicRoute,
  CeramicCoatingRoute: CeramicCoatingRoute,
  CommercialWindowTintRoute: CommercialWindowTintRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PaintProtectionFilmRoute: PaintProtectionFilmRoute,
  PpfRoute: PpfRoute,
  QuoteRoute: QuoteRoute,
  ReviewsRoute: ReviewsRoute,
  TintRoute: TintRoute,
  TintLawsNewMexicoRoute: TintLawsNewMexicoRoute,
  WindowTintRoute: WindowTintRoute,
  BookConfirmedRoute: BookConfirmedRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  BookIndexRoute: BookIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
